export const skillsList = [
    // Development
    "Frontend Dev",
    "Backend Dev",
    "Full Stack Dev",
    "EVM Dev",
    "Solana Dev",
    "Mobile Dev",
    "Smart Contract Dev",
    "DevOps Engineer",
    "Web3 Dev",
    "Game Dev",

    // Design & Creative
    "UI/UX Designer",
    "Graphic Designer",
    "Brand Designer",
    "Motion Designer",
    "Video Editor",
    "Content Creator",
    "Technical Writer",
    "Copywriter",

    // Marketing & Community
    "Digital Marketer",
    "Community Manager",
    "Social Media Manager",
    "Growth Specialist",
    "Brand Manager",
    "Content Strategist",
    "Campaign Manager",

    // Business & Operations
    "Business Developer",
    "Project Manager",
    "Product Manager",
    "Operations Manager",
    "DeFi Analyst",
    "Crypto Researcher",
    "Partnership Manager",
    "DAO Coordinator",

    // Other Specialized Roles
    "Blockchain Analyst",
    "Token Engineer",
    "Community Builder",
    "NFT Specialist",
    "Technical Recruiter",
    "Developer Advocate",
    "Web3 Educator",
  ];

export const countriesList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "North Korea",
  "South Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const tokensList = {
    USDC: "/images/tokens/usdc.png",
    USDT: "/images/tokens/usdt.png",
    // SOL: "/images/tokens/sol.png",
    // BTC: "/images/tokens/btc.png",
    // BNB: "/images/tokens/bnb.png",
    // ETH: "/images/tokens/eth.png",
    // XRP: "/images/tokens/xrp.png",
    // DOGE: "/images/tokens/doge.png",
    // AVAX: "/images/tokens/avax.png",
    // BASE: "/images/tokens/base.png",
    // ADA: "/images/tokens/ada.png",
    // TRX: "/images/tokens/trx.png",
    // TON: "/images/tokens/ton.png",
    // SUI: "/images/tokens/sui.png",
    // DAI: "/images/tokens/dai.png",
    // ARB: "/images/tokens/arb.png",
    // TIA: "/images/tokens/tia.png",
    // AXL: "/images/tokens/axl.png",
    // JUP: "/images/tokens/jup.png",
    // FLOW: "/images/tokens/flow.png",
    // MATIC: "/images/tokens/matic.png",
    // OP: "/images/tokens/op.png",
    // SCROLL: "/images/tokens/scroll.png",
    // ZKSYNC: "/images/tokens/zksync.png",
    // CALL: "/images/tokens/call.png",
};